import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
	return (
		<div className={styles.body_container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header_container}>
				{/* <!-- Headers can come in different sizes, all the way from h1 to h6 --> */}
				<h1>Portfolio</h1>
			</header>

			<nav className={styles.nav_container}>
				<Link href="/blog" passHref>
					<a className={styles.nav_links}>Blog</a>
				</Link>

				<Link href="/about" passHref>
					<a className={styles.nav_links}>About</a>
				</Link>

				<Link href="/projects" passHref>
					<a className={styles.nav_links}>Projects</a>
				</Link>

				<Link href="https://github.com/ggiande" passHref>
					<a className={styles.nav_links}>Github</a>
				</Link>
			</nav>

			<main className={styles.main_container}>
				<h1>Hello, I&apos;m Gian!</h1>
				<pre className={styles.pre_code_container}>
					<p className={styles.code_container}>
						👋 I am currently pursuing a Bachelor&apos;s degree in
						Computer Science
					</p>
					<p className={styles.code_container}>
						💻 I&apos;m a Computer Science major at California State
						University Stanislaus.
					</p>
					<p className={styles.code_container}>
						💼 In the past I have worked as a Software Engineering
						Academic Intern at JPMorgan Chase &38; Co. - Palo Alto
						Office
					</p>
					<p className={styles.code_container}>
						💬 Feel free to talk to me about paving the way for
						students to achieve success through new opportunities
						and being as inclusive as possible.
					</p>

					{/* <!-- Add the terminal division --> */}
					<div id="input" className={styles.terminal}></div>
				</pre>
				<p>
					This website can serve you and your projects. This page is
					hosted directly from your GitHub repository. Just edit,
					push, and your changes are live!
				</p>
			</main>
		</div>
	);
}
